feat(payroll): comprehensive payroll, tax, benefits, and governance updates
Payroll
a. Add the loan deductions in the Payslips: FIXED
b. Gross Earnings (Total Compensation) should be empty when no total amnt of hrs worked.: No need to fix cause there's an deduction one.
c. Basic Pay should be the rate x period and shouldn't be changeable: fixed
f. Net pay should be the one changeable computations is Gross Pay (total wrk + additional pay) - Deductions ( total absences and lates + gov ded + loans) = Net pay : FIXED

g. Summary View on Payroll Period
= remove the received by and the signature below each page (add the signatory only on the last page): FIXED

h. Payroll Period
= Process Batch button should be accessible also when the period is over (in cases na makalimutan siya i-process)
= 1 week timelength only after the period ends
: Fixed + Added a new tab in the payroll for batch can configure

Settings
a. Tax changes should have confirmation modal for not accidentally change it and like add a button of locking it. : FIXED

User Side
a. The payslip releases even the admin didn't release the payroll yet
a.1. The loans & others tab didn't fetch data from payslip but in the admin side it fetch (or because the payroll didn't released yet)
: FIXED

General
- Remove the Intern & Part-Time
: FIXED

Request
a. Removes the loan nudge request : FIXED

ADMIN SIDE
- Edit Profile
error: computeMonthlyShares is not a function
appears tuwing ni click yung "save changes" na button
: FIXED
A comprehensive breakdown of computations
The BIR Tax is computed via Monthly Bracket but deduct every period